[CmdletBinding()]
param(
    [string]$RootPath = (Join-Path $PSScriptRoot '..\..'),
    [string[]]$Scope,
    [switch]$Check
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'SpecTraceMigration.Common.ps1')

$repoRoot = Get-SpecTraceMigrationRepoRoot -RootPath $RootPath
$jsonPaths = @(Get-SpecTraceCanonicalJsonArtifactPaths -RepoRoot $repoRoot -Scope $Scope)
if ($jsonPaths.Count -eq 0) {
    throw 'No canonical .json artifacts were found to render.'
}

$generatorComment = 'Generated from sibling .json by scripts/spec-trace/Render-SpecTraceMarkdownFromJson.ps1. Do not edit this file directly.'
$mismatches = New-Object System.Collections.Generic.List[string]

foreach ($jsonPath in $jsonPaths) {
    $artifact = Import-JsonArtifact -JsonPath $jsonPath
    $markdownPath = [System.IO.Path]::ChangeExtension($jsonPath, '.md')
    $rendered = Render-ArtifactMarkdown -Artifact $artifact -GeneratorComment $generatorComment

    if ($Check) {
        if (Test-Path -LiteralPath $markdownPath) {
            $current = ((Get-Content -LiteralPath $markdownPath -Raw) -replace "`r`n", "`n" -replace "`r", "`n").TrimEnd()
            $expected = (($rendered -replace "`r`n", "`n" -replace "`r", "`n")).TrimEnd()
            if ($current -ne $expected) {
                $mismatches.Add((Get-RepoRelativePath -RepoRoot $repoRoot -Path $markdownPath))
            }
        }
        continue
    }

    Set-Content -LiteralPath $markdownPath -NoNewline -Value $rendered
}

if ($Check) {
    if ($mismatches.Count -gt 0) {
        throw "Rendered Markdown is out of date for: $($mismatches -join ', ')"
    }

    Write-Output "Checked $($jsonPaths.Count) artifact(s) for stale Markdown views."
    exit 0
}

Write-Output "Rendered $($jsonPaths.Count) Markdown views from sibling .json files."
